const getImage = (category) => {
    const urls = {
        grains: "https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&w=400&q=80",
        pulses: "https://images.unsplash.com/photo-1537284693309-8874136952d7?auto=format&w=400&q=80",
        spices: "https://images.unsplash.com/photo-1599905961996-ba647161b9fc?auto=format&w=400&q=80",
        oils: "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?auto=format&w=400&q=80",
        dairy: "https://images.unsplash.com/photo-1550583724-b2692b85b150?auto=format&w=400&q=80",
        produce: "https://images.unsplash.com/photo-1592924357228-91a4daadcfea?auto=format&w=400&q=80",
        meat: "https://images.unsplash.com/photo-1604503468506-a8da13d82791?auto=format&w=400&q=80",
        bakery: "https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&w=400&q=80",
        pantry: "https://images.unsplash.com/photo-1581456495146-65a71b2c8e52?auto=format&w=400&q=80",
    };
    return urls[category] || urls.pantry;
};

export const INGREDIENTS_DB = [
  { name: "Rice (Basmati, Sona Masoori)", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/07/Khyma_and_Basmati_rice.jpg/500px-Khyma_and_Basmati_rice.jpg", category: "Pantry" },
  { name: "Wheat flour (Atta)", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/26/Atta_flour.jpg/500px-Atta_flour.jpg", category: "Pantry" },
  { name: "Rava (Sooji)", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Dosa_at_Sri_Ganesha_Restauran%2C_Bangkok_%2844570742744%29.jpg/500px-Dosa_at_Sri_Ganesha_Restauran%2C_Bangkok_%2844570742744%29.jpg", category: "Pantry" },
  { name: "Poha (Flattened rice)", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/80/Poha.jpg/500px-Poha.jpg", category: "Pantry" },
  { name: "Vermicelli (Seviyan)", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f2/Fideo_%28coiled_vermicelli%29.JPG/500px-Fideo_%28coiled_vermicelli%29.JPG", category: "Pantry" },
  { name: "Oats", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/Good_Food_Display_-_NCI_Visuals_Online.jpg/500px-Good_Food_Display_-_NCI_Visuals_Online.jpg", category: "Pantry" },
  { name: "Cornflakes", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Kellogg%27s_Corn_Flakes%2C_with_milk.jpg/500px-Kellogg%27s_Corn_Flakes%2C_with_milk.jpg", category: "Pantry" },
  { name: "Toor dal (Arhar)", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/Cajanus_cajan_Blanco1.167-cropped.jpg/500px-Cajanus_cajan_Blanco1.167-cropped.jpg", category: "Pantry" },
  { name: "Moong dal (Yellow/Green)", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/86/Mung_beans_%28Vigna_radiata%29.jpg/500px-Mung_beans_%28Vigna_radiata%29.jpg", category: "Pantry" },
  { name: "Urad dal", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Black_gram.jpg/500px-Black_gram.jpg", category: "Pantry" },
  { name: "Chana dal", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/89/Chickpea_BNC.jpg/500px-Chickpea_BNC.jpg", category: "Pantry" },
  { name: "Rajma (Kidney beans)", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/27/Red_Rajma_BNC.jpg/500px-Red_Rajma_BNC.jpg", category: "Pantry" },
  { name: "Kabuli chana (Chickpeas)", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/89/Chickpea_BNC.jpg/500px-Chickpea_BNC.jpg", category: "Pantry" },
  { name: "Black chana", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/89/Chickpea_BNC.jpg/500px-Chickpea_BNC.jpg", category: "Pantry" },
  { name: "Turmeric powder (Haldi)", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ab/Turmeric_inflorescence.jpg/500px-Turmeric_inflorescence.jpg", category: "Pantry" },
  { name: "Red chilli powder", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/00/BolivianChilePowder2.JPG/500px-BolivianChilePowder2.JPG", category: "Pantry" },
  { name: "Coriander powder", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/Curry_powder_in_the_spice-bazaar_in_Istanbul.jpg/500px-Curry_powder_in_the_spice-bazaar_in_Istanbul.jpg", category: "Pantry" },
  { name: "Cumin seeds (Jeera)", image: "https://upload.wikimedia.org/wikipedia/commons/5/58/Cuminum_cyminum_-_K%C3%B6hler%E2%80%93s_Medizinal-Pflanzen-198.jpg", category: "Pantry" },
  { name: "Mustard seeds (Rai)", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/35/Mustard.png/500px-Mustard.png", category: "Pantry" },
  { name: "Garam masala", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/58/Garammasalaphoto.jpg/500px-Garammasalaphoto.jpg", category: "Pantry" },
  { name: "Sambar powder", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bb/Pumpkin_sambar.JPG/500px-Pumpkin_sambar.JPG", category: "Pantry" },
  { name: "Hing (Asafoetida)", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Taj_Mahal_-_Lamb_Curry_Madras.jpg/500px-Taj_Mahal_-_Lamb_Curry_Madras.jpg", category: "Pantry" },
  { name: "Cooking oil (Sunflower/Mustard)", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/49/Olive_oil_from_Oneglia.jpg/500px-Olive_oil_from_Oneglia.jpg", category: "Pantry" },
  { name: "Vinegar", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Eguilles_20110828_14.jpg/500px-Eguilles_20110828_14.jpg", category: "Pantry" },
  { name: "Soy sauce", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/63/Soy_sauce_2.jpg/500px-Soy_sauce_2.jpg", category: "Pantry" },
  { name: "Tomato ketchup", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Heinz_Tomato_Ketchup%2C_Canada_%28front%29%2C_2026-02-19.jpg/500px-Heinz_Tomato_Ketchup%2C_Canada_%28front%29%2C_2026-02-19.jpg", category: "Pantry" },
  { name: "Green chutney / Pickles (Achar)", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/14/Chutneykarnataka.jpg/500px-Chutneykarnataka.jpg", category: "Pantry" },
  { name: "Sugar", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3c/Sucre_blanc_cassonade_complet_rapadura.jpg/500px-Sucre_blanc_cassonade_complet_rapadura.jpg", category: "Pantry" },
  { name: "Jaggery (Gur)", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/09/Sa-indian-gud.jpg/500px-Sa-indian-gud.jpg", category: "Pantry" },
  { name: "Salt", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f0/ProsciuttoSeaSalt.JPG/500px-ProsciuttoSeaSalt.JPG", category: "Pantry" },
  { name: "Tea powder / Coffee", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bd/Roasted_grain_beverage_kawa_zbozowa_Poland.jpg/500px-Roasted_grain_beverage_kawa_zbozowa_Poland.jpg", category: "Pantry" },
  { name: "Dry fruits (Almonds, Cashews)", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/72/Chestnut.jpg/500px-Chestnut.jpg", category: "Pantry" },
  { name: "Milk", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/Glass_of_Milk_%2833657535532%29.jpg/500px-Glass_of_Milk_%2833657535532%29.jpg", category: "Dairy" },
  { name: "Curd (Dahi)", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2d/Dahi_bhalla_or_dahi_wada_or_dahi_bada.PNG/500px-Dahi_bhalla_or_dahi_wada_or_dahi_bada.PNG", category: "Dairy" },
  { name: "Paneer", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/Panir_Paneer_Indian_cheese_fresh.jpg/500px-Panir_Paneer_Indian_cheese_fresh.jpg", category: "Dairy" },
  { name: "Butter", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/%C5%A0v%C3%A9dsk%C3%BD_kol%C3%A1%C4%8D_naruby_904_%28cropped%29.JPG/500px-%C5%A0v%C3%A9dsk%C3%BD_kol%C3%A1%C4%8D_naruby_904_%28cropped%29.JPG", category: "Dairy" },
  { name: "Cheese (Mozzarella)", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/57/Mozzarella_di_bufala3.jpg/500px-Mozzarella_di_bufala3.jpg", category: "Dairy" },
  { name: "Cream (Malai)", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ae/Ras_Malai_2.JPG/500px-Ras_Malai_2.JPG", category: "Dairy" },
  { name: "Buttermilk (Chaas)", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f9/Mint_lassi.jpg/500px-Mint_lassi.jpg", category: "Dairy" },
  { name: "Lassi (Sweet/Salted)", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f1/Salt_lassi.jpg/500px-Salt_lassi.jpg", category: "Dairy" },
  { name: "Condensed milk", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/2016-03-26-Gezuckerte_Kondensmilch-4699.jpg/500px-2016-03-26-Gezuckerte_Kondensmilch-4699.jpg", category: "Dairy" },
  { name: "Ghee", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c7/Home_made_Ghee.jpg/500px-Home_made_Ghee.jpg", category: "Dairy" },
  { name: "Onion", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/Mixed_onions.jpg/500px-Mixed_onions.jpg", category: "Produce" },
  { name: "Potato", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ab/Patates.jpg/500px-Patates.jpg", category: "Produce" },
  { name: "Tomato", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/89/Tomato_je.jpg/500px-Tomato_je.jpg", category: "Produce" },
  { name: "Green chilli", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/50/Madame_Jeanette_and_other_chillies.jpg/500px-Madame_Jeanette_and_other_chillies.jpg", category: "Produce" },
  { name: "Ginger", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/18/Koeh-146-no_text.jpg/500px-Koeh-146-no_text.jpg", category: "Produce" },
  { name: "Garlic", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7b/Black_garlic.jpg/500px-Black_garlic.jpg", category: "Produce" },
  { name: "Carrot", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fe/Carrot_cake_at_America_Graffiti_%28cropped%29.jpg/500px-Carrot_cake_at_America_Graffiti_%28cropped%29.jpg", category: "Produce" },
  { name: "Beans", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0b/Baked_beans_in_tomato_sauce.jpg/500px-Baked_beans_in_tomato_sauce.jpg", category: "Produce" },
  { name: "Brinjal (Eggplant)", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/14/Corbeille_d%27aubergines.JPG/500px-Corbeille_d%27aubergines.JPG", category: "Produce" },
  { name: "Capsicum", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d2/Capsicum_annuum_-_K%C3%B6hler%E2%80%93s_Medizinal-Pflanzen-027.jpg/500px-Capsicum_annuum_-_K%C3%B6hler%E2%80%93s_Medizinal-Pflanzen-027.jpg", category: "Produce" },
  { name: "Cauliflower", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/Chou-fleur_02.jpg/500px-Chou-fleur_02.jpg", category: "Produce" },
  { name: "Cabbage", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Cabbage_and_cross_section_on_white.jpg/500px-Cabbage_and_cross_section_on_white.jpg", category: "Produce" },
  { name: "Spinach (Palak)", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b7/Palakpaneer_Rayagada_Odisha_0009.jpg/500px-Palakpaneer_Rayagada_Odisha_0009.jpg", category: "Produce" },
  { name: "Coriander (Dhaniya)", image: "https://upload.wikimedia.org/wikipedia/commons/1/13/Coriandrum_sativum_-_K%C3%B6hler%E2%80%93s_Medizinal-Pflanzen-193.jpg", category: "Produce" },
  { name: "Mint (Pudina)", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/64/Peppermint_tea_2.jpg/500px-Peppermint_tea_2.jpg", category: "Produce" },
  { name: "Fenugreek leaves (Methi)", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/ce/Illustration_Trigonella_foenum-graecum0_clean.jpg/500px-Illustration_Trigonella_foenum-graecum0_clean.jpg", category: "Produce" },
  { name: "Banana", image: "https://upload.wikimedia.org/wikipedia/commons/d/de/Bananavarieties.jpg", category: "Produce" },
  { name: "Apple", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a6/Pink_lady_and_cross_section.jpg/500px-Pink_lady_and_cross_section.jpg", category: "Produce" },
  { name: "Mango", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/74/Mangos_-_single_and_halved.jpg/500px-Mangos_-_single_and_halved.jpg", category: "Produce" },
  { name: "Orange", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d8/Delicatearch.png/500px-Delicatearch.png", category: "Produce" },
  { name: "Papaya", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/Carica_papaya_-_K%C3%B6hler%E2%80%93s_Medizinal-Pflanzen-029.jpg/500px-Carica_papaya_-_K%C3%B6hler%E2%80%93s_Medizinal-Pflanzen-029.jpg", category: "Produce" },
  { name: "Guava", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/88/Guava_pink_fruit.jpg/500px-Guava_pink_fruit.jpg", category: "Produce" },
  { name: "Pomegranate", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6a/Pomegranate_Juice_%282019%29.jpg/500px-Pomegranate_Juice_%282019%29.jpg", category: "Produce" },
  { name: "Chicken", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/57/Chickens_in_market.jpg/500px-Chickens_in_market.jpg", category: "Meat" },
  { name: "Mutton (Goat meat)", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8c/Lamb_meat_%281%29.jpg/500px-Lamb_meat_%281%29.jpg", category: "Meat" },
  { name: "Fish (Rohu, Katla)", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Rohu_at_Giant_Hypermarket_Kota_Damansara_20230203_105829.jpg/500px-Rohu_at_Giant_Hypermarket_Kota_Damansara_20230203_105829.jpg", category: "Meat" },
  { name: "Prawns", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Spicy_fried_King_Prawns.jpg/500px-Spicy_fried_King_Prawns.jpg", category: "Meat" },
  { name: "Eggs", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3f/Huevo_frito.jpg/500px-Huevo_frito.jpg", category: "Meat" },
  { name: "Tofu", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/03/Japanese_SilkyTofu_%28Kinugoshi_Tofu%29.JPG/500px-Japanese_SilkyTofu_%28Kinugoshi_Tofu%29.JPG", category: "Produce" },
  { name: "Soya chunks (Nutrela)", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/82/Soybean.USDA.jpg/500px-Soybean.USDA.jpg", category: "Pantry" },
  { name: "Bread (White/Brown)", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8b/Kommissbrot.jpg/500px-Kommissbrot.jpg", category: "Bakery" },
  { name: "Pav (for pav bhaji)", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Bambayya_Pav_bhaji.jpg/500px-Bambayya_Pav_bhaji.jpg", category: "Bakery" },
  { name: "Buns", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ac/HomeHotCross.jpg/500px-HomeHotCross.jpg", category: "Bakery" },
  { name: "Rusk (Toast biscuits)", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/79/Zwieback-1.jpg/500px-Zwieback-1.jpg", category: "Bakery" },
  { name: "Biscuits (Parle-G, Marie)", image: "https://upload.wikimedia.org/wikipedia/commons/0/05/Parle_G_logo.jpg", category: "Bakery" },
  { name: "Cookies", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b4/Choco_chip_cookie.png/500px-Choco_chip_cookie.png", category: "Bakery" },
  { name: "Cakes", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/42/Chocolate_angel_food_cake_with_various_toppings.jpg/500px-Chocolate_angel_food_cake_with_various_toppings.jpg", category: "Bakery" },
  { name: "Muffins", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e8/Harborview_Bistro_%26_Bar_-_January_2024_-_Sarah_Stierch_08.jpg/500px-Harborview_Bistro_%26_Bar_-_January_2024_-_Sarah_Stierch_08.jpg", category: "Bakery" }
];
